query StaffMedia($staffId: Int, $onList: Boolean, $type: MediaType, $page: Int, $perPage: Int) {
    Staff(id: $staffId) {
        staffMedia(page: $page, perPage: $perPage, sort: [START_DATE_DESC], onList: $onList, type: $type) {
            edges {
                id
                node {
                    ...BasicMediaDetails
                    coverImage {
                        large
                    }
                    mediaListEntry {
                        ...BasicMediaListEntry
                    }
                }
                staffRole
            }
            pageInfo {
                ...CommonPage
            }
        }
    }
}