query UserFavoritesCharacter($userId: Int, $page: Int, $perPage: Int) {
    User(id: $userId) {
        favourites {
            characters(page: $page, perPage: $perPage) {
                edges {
                    id
                    favouriteOrder
                    node {
                        id
                        name {
                            userPreferred
                        }
                        image {
                            large
                        }
                    }
                }
                pageInfo {
                    ...CommonPage
                }
            }
        }
    }
}
