query StudioMedia($studioId: Int, $sort: [MediaSort], $onList: Boolean, $page: Int, $perPage: Int) {
    Studio(id: $studioId) {
        media(isMain: true, page: $page, perPage: $perPage, sort: $sort, onList: $onList) {
            ...CommonStudioMedia
            pageInfo {
                ...CommonPage
            }
        }
    }
}

fragment CommonStudioMedia on MediaConnection {
    nodes {
        id
        coverImage {
            large
        }
        isAdult
        title {
            userPreferred
        }
        startDate {
            year
        }
        mediaListEntry {
            id
            status
        }
    }
}
