name: Android Build Release FOSS APK

on:
  push:
    branches:
      - 'master'
    paths:
      - 'version.properties'
  workflow_dispatch:
    inputs:
      single_apk:
        description: 'Build only the universal apk'
        type: boolean

env:
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v2
        id: android_keystore
        with:
          fileName: "android_keystore.keystore"
          encodedString: ${{secrets.KEYSTORE_FILE}}
      
      - name: Accept Android SDK license
        run: echo "y" | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"

      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          java-version: 17
          distribution: temurin

      - if: ${{ inputs.single_apk == true }}
        run: sed -i -e '/isEnable/s/true/false/' app/build.gradle.kts

      - name: Build Android release
        run: fastlane release
        env:
          KEYSTORE_FILE: ${{steps.android_keystore.outputs.filePath}}
          KEYSTORE_PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
          KEY_ALIAS: ${{secrets.KEY_ALIAS}}
          KEY_PASSWORD: ${{secrets.KEY_PASSWORD}}

      - name: Extract version
        id: get_version
        run: |
          VERSION=$(grep '^name =' version.properties | cut -d'=' -f2 | xargs)
          CODE=$(grep '^code =' version.properties | cut -d'=' -f2 | xargs)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "code=$CODE" >> $GITHUB_OUTPUT

      - name: Check for Release/Beta prefix
        id: check_prefix
        run: |
          MSG=$(echo "${{ github.event.head_commit.message }}" | head -n 1)
          if [[ $MSG == beta:* ]]; then
            echo "is_release=true" >> $GITHUB_OUTPUT
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
            echo "tag_name=beta-${{ steps.get_version.outputs.code }}" >> $GITHUB_OUTPUT
          elif [[ $MSG == release:* ]]; then
            echo "is_release=true" >> $GITHUB_OUTPUT
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
            echo "tag_name=v${{ steps.get_version.outputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        if: steps.check_prefix.outputs.is_release == 'true'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.check_prefix.outputs.tag_name }}
          name: ${{ steps.check_prefix.outputs.tag_name }}
          prerelease: ${{ steps.check_prefix.outputs.is_prerelease == 'true' }}
          files: app/build/outputs/apk/foss/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
